version: '3.9'
services:
  postgres17:
    image: postgres:17
    container_name: postgres17
    volumes:
      - /volume1/data_store/PaperlessStore/db17:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  postgres18:
    image: postgres:18
    container_name: postgres18
    volumes:
      - /volume1/data_store/PaperlessStore/db18:/var/lib/postgresql
    ports:
      - 15433:5432
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
